local ui = {}
local player = game.Players.LocalPlayer
local character = player.Character or player.CharacterAdded:Wait()
local hrp = character:FindFirstChild("HumanoidRootPart")
local backpack = player.Backpack

function ui.getUI()
	local EasyBuildUI = Instance.new("ScreenGui")
	EasyBuildUI.Parent = game.CoreGui --[[ e.g. PlayerGui ]]
	EasyBuildUI.Enabled = true
	EasyBuildUI.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
	EasyBuildUI.ResetOnSpawn = true
	EasyBuildUI.IgnoreGuiInset = false
	EasyBuildUI.Name = "EasyBuildUI"
	EasyBuildUI.DisplayOrder = 0
	EasyBuildUI.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
	EasyBuildUI.ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets
	EasyBuildUI.ClipToDeviceSafeArea = true
	local BrickImage = Instance.new("ImageLabel")
	BrickImage.Parent = EasyBuildUI
	BrickImage.LayoutOrder = 0
	BrickImage.Active = true
	BrickImage.Interactable = true
	BrickImage.SizeConstraint = Enum.SizeConstraint.RelativeXY
	BrickImage.ZIndex = 1
	BrickImage.BorderSizePixel = 5
	BrickImage.SliceCenter = Rect.new(0, 0, 0, 0)
	BrickImage.Draggable = true
	BrickImage.ScaleType = Enum.ScaleType.Tile
	BrickImage.Transparency = 0
	BrickImage.SelectionOrder = 0
	BrickImage.BackgroundColor3 = Color3.fromRGB(255, 174, 82)
	BrickImage.ImageTransparency = 0
	BrickImage.Selectable = false
	BrickImage.AnchorPoint = Vector2.new(0, 0)
	BrickImage.Image = "rbxassetid://6927295847"
	BrickImage.TileSize = UDim2.new(0.10000000149011612, 0, 0.10000000149011612, 0)
	BrickImage.BorderColor = BrickColor.new("Really black")
	BrickImage.ImageContent = Content.fromUri("rbxassetid://6927295847")
	BrickImage.AutomaticSize = Enum.AutomaticSize.None
	BrickImage.Size = UDim2.new(0.3799999952316284, 0, 0.5966587066650391, 0)
	BrickImage.ClipsDescendants = false
	BrickImage.BorderColor3 = Color3.fromRGB(0, 0, 0)
	BrickImage.Visible = true
	BrickImage.ImageColor3 = Color3.fromRGB(255, 255, 255)
	BrickImage.BorderMode = Enum.BorderMode.Outline
	BrickImage.Rotation = 0
	BrickImage.ImageRectOffset = Vector2.new(0, 0)
	BrickImage.BackgroundTransparency = 0
	BrickImage.Position = UDim2.new(0.3096773326396942, -60, 0.20167064666748047, -49)
	BrickImage.SliceScale = 1
	BrickImage.ImageRectSize = Vector2.new(0, 0)
	BrickImage.ResampleMode = Enum.ResamplerMode.Default
	BrickImage.Name = "BrickImage"
	local Title = Instance.new("TextLabel")
	Title.Parent = BrickImage
	Title.LayoutOrder = 0
	Title.FontSize = Enum.FontSize.Size14
	Title.TextDirection = Enum.TextDirection.Auto
	Title.Active = false
	Title.Interactable = true
	Title.TextStrokeTransparency = 1
	Title.TextTruncate = Enum.TextTruncate.None
	Title.SizeConstraint = Enum.SizeConstraint.RelativeXY
	Title.ZIndex = 1
	Title.BorderSizePixel = 0
	Title.Draggable = false
	Title.RichText = false
	Title.SelectionOrder = 0
	Title.TextYAlignment = Enum.TextYAlignment.Center
	Title.TextScaled = true
	Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Title.FontFace = Font.new("rbxasset://fonts/families/ComicNeueAngular.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic)
	Title.BorderMode = Enum.BorderMode.Outline
	Title.Selectable = false
	Title.OpenTypeFeatures = ""
	Title.AnchorPoint = Vector2.new(0, 0)
	Title.BorderColor = BrickColor.new("Really black")
	Title.Visible = true
	Title.TextXAlignment = Enum.TextXAlignment.Center
	Title.AutomaticSize = Enum.AutomaticSize.None
	Title.Size = UDim2.new(0.3752122223377228, 0, 0.08399999886751175, 0)
	Title.TextWrapped = true
	Title.TextWrap = true
	Title.TextTransparency = 0
	Title.ClipsDescendants = false
	Title.BorderColor3 = Color3.fromRGB(0, 0, 0)
	Title.Text = "Easy Build (V1.0)"
	Title.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	Title.LineHeight = 1
	Title.Rotation = 0
	Title.Font = Enum.Font.Unknown
	Title.BackgroundTransparency = 1
	Title.Position = UDim2.new(0, 0, 0.9160000085830688, 0)
	Title.TextSize = 14
	Title.MaxVisibleGraphemes = -1
	Title.TextColor3 = Color3.fromRGB(0, 0, 0)
	Title.Name = "Title"
	local CloseCircle = Instance.new("TextButton")
	CloseCircle.Parent = BrickImage
	CloseCircle.LayoutOrder = 0
	CloseCircle.FontSize = Enum.FontSize.Size14
	CloseCircle.LineHeight = 1
	CloseCircle.Active = true
	CloseCircle.Interactable = true
	CloseCircle.TextStrokeTransparency = 1
	CloseCircle.TextTruncate = Enum.TextTruncate.None
	CloseCircle.SizeConstraint = Enum.SizeConstraint.RelativeXY
	CloseCircle.ZIndex = 1
	CloseCircle.BorderSizePixel = 0
	CloseCircle.Draggable = false
	CloseCircle.RichText = false
	CloseCircle.Modal = false
	CloseCircle.AutoButtonColor = true
	CloseCircle.SelectionOrder = 0
	CloseCircle.TextYAlignment = Enum.TextYAlignment.Center
	CloseCircle.TextScaled = false
	CloseCircle.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
	CloseCircle.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	CloseCircle.BorderMode = Enum.BorderMode.Outline
	CloseCircle.Selectable = true
	CloseCircle.OpenTypeFeatures = ""
	CloseCircle.AnchorPoint = Vector2.new(0, 0)
	CloseCircle.Visible = true
	CloseCircle.TextXAlignment = Enum.TextXAlignment.Center
	CloseCircle.BorderColor = BrickColor.new("Really black")
	CloseCircle.TextWrapped = false
	CloseCircle.Selected = false
	CloseCircle.AutomaticSize = Enum.AutomaticSize.None
	CloseCircle.Size = UDim2.new(0.08488964289426804, 0, 0.10000000149011612, 0)
	CloseCircle.TextWrap = false
	CloseCircle.TextTransparency = 0
	CloseCircle.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	CloseCircle.ClipsDescendants = false
	CloseCircle.BorderColor3 = Color3.fromRGB(0, 0, 0)
	CloseCircle.Text = ""
	CloseCircle.TextSize = 14
	CloseCircle.TextDirection = Enum.TextDirection.Auto
	CloseCircle.Rotation = 0
	CloseCircle.Font = Enum.Font.SourceSans
	CloseCircle.BackgroundTransparency = 0
	CloseCircle.Position = UDim2.new(0.8998302221298218, 0, 0.01304347813129425, 0)
	CloseCircle.TextColor3 = Color3.fromRGB(0, 0, 0)
	CloseCircle.MaxVisibleGraphemes = -1
	CloseCircle.Style = Enum.ButtonStyle.Custom
	CloseCircle.Name = "CloseCircle"
	local UICorner = Instance.new("UICorner")
	UICorner.Parent = CloseCircle
	UICorner.Name = "UICorner"
	UICorner.CornerRadius = UDim.new(100, 9)
	local TeamScroll = Instance.new("ScrollingFrame")
	TeamScroll.Parent = BrickImage
	TeamScroll.LayoutOrder = 0
	TeamScroll.Active = true
	TeamScroll.Interactable = true
	TeamScroll.ScrollingDirection = Enum.ScrollingDirection.XY
	TeamScroll.SizeConstraint = Enum.SizeConstraint.RelativeXY
	TeamScroll.ZIndex = 1
	TeamScroll.BorderSizePixel = 5
	TeamScroll.CanvasSize = UDim2.new(0, 0, 2, 0)
	TeamScroll.Draggable = false
	TeamScroll.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
	TeamScroll.CanvasPosition = Vector2.new(0, 0)
	TeamScroll.ElasticBehavior = Enum.ElasticBehavior.WhenScrollable
	TeamScroll.Transparency = 0
	TeamScroll.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
	TeamScroll.SelectionOrder = 0
	TeamScroll.BackgroundColor3 = Color3.fromRGB(75, 75, 75)
	TeamScroll.MidImageContent = Content.fromUri("rbxasset://textures/ui/Scroll/scroll-middle.png")
	TeamScroll.BorderMode = Enum.BorderMode.Outline
	TeamScroll.Selectable = true
	TeamScroll.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
	TeamScroll.AnchorPoint = Vector2.new(0, 0)
	TeamScroll.BorderColor = BrickColor.new("Really black")
	TeamScroll.Visible = true
	TeamScroll.AutomaticSize = Enum.AutomaticSize.None
	TeamScroll.Size = UDim2.new(0.30899831652641296, 0, 0.6919999718666077, 0)
	TeamScroll.ScrollBarImageColor3 = Color3.fromRGB(0, 0, 0)
	TeamScroll.VerticalScrollBarInset = Enum.ScrollBarInset.None
	TeamScroll.TopImageContent = Content.fromUri("rbxasset://textures/ui/Scroll/scroll-top.png")
	TeamScroll.ClipsDescendants = true
	TeamScroll.BorderColor3 = Color3.fromRGB(0, 0, 0)
	TeamScroll.ScrollBarThickness = 0
	TeamScroll.AutomaticCanvasSize = Enum.AutomaticSize.None
	TeamScroll.ScrollBarImageTransparency = 0
	TeamScroll.Rotation = 0
	TeamScroll.Position = UDim2.new(0.06960950791835785, 0, 0.12999999523162842, 0)
	TeamScroll.BackgroundTransparency = 0
	TeamScroll.BottomImageContent = Content.fromUri("rbxasset://textures/ui/Scroll/scroll-bottom.png")
	TeamScroll.ScrollingEnabled = true
	TeamScroll.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
	TeamScroll.Name = "TeamScroll"
	TeamScroll.HorizontalScrollBarInset = Enum.ScrollBarInset.None
	local UIListLayout = Instance.new("UIListLayout")
	UIListLayout.Parent = TeamScroll
	UIListLayout.FillDirection = Enum.FillDirection.Vertical
	UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
	UIListLayout.HorizontalFlex = Enum.UIFlexAlignment.None
	UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
	UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	UIListLayout.Name = "UIListLayout"
	UIListLayout.Wraps = false
	UIListLayout.Padding = UDim.new(0.009999999776482582, 0)
	UIListLayout.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
	UIListLayout.VerticalFlex = Enum.UIFlexAlignment.None
	local TextButton = Instance.new("TextButton")
	TextButton.Parent = BrickImage
	TextButton.LayoutOrder = 0
	TextButton.FontSize = Enum.FontSize.Size14
	TextButton.LineHeight = 1
	TextButton.Active = true
	TextButton.Interactable = true
	TextButton.TextStrokeTransparency = 1
	TextButton.TextTruncate = Enum.TextTruncate.None
	TextButton.SizeConstraint = Enum.SizeConstraint.RelativeXY
	TextButton.ZIndex = 1
	TextButton.BorderSizePixel = 3
	TextButton.Draggable = false
	TextButton.RichText = false
	TextButton.Modal = false
	TextButton.AutoButtonColor = true
	TextButton.SelectionOrder = 0
	TextButton.TextYAlignment = Enum.TextYAlignment.Center
	TextButton.TextScaled = true
	TextButton.BackgroundColor3 = Color3.fromRGB(9, 186, 0)
	TextButton.FontFace = Font.new("rbxasset://fonts/families/ComicNeueAngular.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	TextButton.BorderMode = Enum.BorderMode.Outline
	TextButton.Selectable = true
	TextButton.OpenTypeFeatures = ""
	TextButton.AnchorPoint = Vector2.new(0, 0)
	TextButton.Visible = true
	TextButton.TextXAlignment = Enum.TextXAlignment.Center
	TextButton.BorderColor = BrickColor.new("Really black")
	TextButton.TextWrapped = true
	TextButton.Selected = false
	TextButton.AutomaticSize = Enum.AutomaticSize.None
	TextButton.Size = UDim2.new(0.33955857157707214, 0, 0.10000000149011612, 0)
	TextButton.TextWrap = true
	TextButton.TextTransparency = 0
	TextButton.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	TextButton.ClipsDescendants = false
	TextButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
	TextButton.Text = "STEAL BUILD"
	TextButton.TextSize = 14
	TextButton.TextDirection = Enum.TextDirection.Auto
	TextButton.Rotation = 0
	TextButton.Font = Enum.Font.Unknown
	TextButton.BackgroundTransparency = 0
	TextButton.Position = UDim2.new(0.5178267955780029, 0, 0.722000002861023, 0)
	TextButton.TextColor3 = Color3.fromRGB(0, 0, 0)
	TextButton.MaxVisibleGraphemes = -1
	TextButton.Style = Enum.ButtonStyle.Custom
	TextButton.Name = "TextButton"
	local PlaceHolder = Instance.new("TextButton")
	PlaceHolder.Parent = BrickImage
	PlaceHolder.LayoutOrder = 0
	PlaceHolder.FontSize = Enum.FontSize.Size14
	PlaceHolder.LineHeight = 1
	PlaceHolder.Active = true
	PlaceHolder.Interactable = true
	PlaceHolder.TextStrokeTransparency = 1
	PlaceHolder.TextTruncate = Enum.TextTruncate.None
	PlaceHolder.SizeConstraint = Enum.SizeConstraint.RelativeXY
	PlaceHolder.ZIndex = 1
	PlaceHolder.BorderSizePixel = 0
	PlaceHolder.Draggable = false
	PlaceHolder.RichText = false
	PlaceHolder.Modal = false
	PlaceHolder.AutoButtonColor = true
	PlaceHolder.SelectionOrder = 0
	PlaceHolder.TextYAlignment = Enum.TextYAlignment.Center
	PlaceHolder.TextScaled = true
	PlaceHolder.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	PlaceHolder.FontFace = Font.new("rbxasset://fonts/families/ComicNeueAngular.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	PlaceHolder.BorderMode = Enum.BorderMode.Outline
	PlaceHolder.Selectable = true
	PlaceHolder.OpenTypeFeatures = ""
	PlaceHolder.AnchorPoint = Vector2.new(0, 0)
	PlaceHolder.Visible = false
	PlaceHolder.TextXAlignment = Enum.TextXAlignment.Center
	PlaceHolder.BorderColor = BrickColor.new("Really black")
	PlaceHolder.TextWrapped = true
	PlaceHolder.Selected = false
	PlaceHolder.AutomaticSize = Enum.AutomaticSize.None
	PlaceHolder.Size = UDim2.new(0.9890112280845642, 0, 0.08348798006772995, 0)
	PlaceHolder.TextWrap = true
	PlaceHolder.TextTransparency = 0
	PlaceHolder.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	PlaceHolder.ClipsDescendants = false
	PlaceHolder.BorderColor3 = Color3.fromRGB(0, 0, 0)
	PlaceHolder.Text = "TEAM NAME"
	PlaceHolder.TextSize = 14
	PlaceHolder.TextDirection = Enum.TextDirection.Auto
	PlaceHolder.Rotation = 0
	PlaceHolder.Font = Enum.Font.Unknown
	PlaceHolder.BackgroundTransparency = 0
	PlaceHolder.Position = UDim2.new(0, 0, 0, 0)
	PlaceHolder.TextColor3 = Color3.fromRGB(0, 0, 0)
	PlaceHolder.MaxVisibleGraphemes = -1
	PlaceHolder.Style = Enum.ButtonStyle.Custom
	PlaceHolder.Name = "PlaceHolder"
	local BlocksPlacedLabel: TextLabel = Instance.new("TextLabel")
	BlocksPlacedLabel.Parent = BrickImage
	BlocksPlacedLabel.LayoutOrder = 0
	BlocksPlacedLabel.FontSize = Enum.FontSize.Size14
	BlocksPlacedLabel.TextDirection = Enum.TextDirection.Auto
	BlocksPlacedLabel.Active = false
	BlocksPlacedLabel.Interactable = true
	BlocksPlacedLabel.TextStrokeTransparency = 1
	BlocksPlacedLabel.TextTruncate = Enum.TextTruncate.None
	BlocksPlacedLabel.SizeConstraint = Enum.SizeConstraint.RelativeXY
	BlocksPlacedLabel.ZIndex = 1
	BlocksPlacedLabel.BorderSizePixel = 0
	BlocksPlacedLabel.Draggable = false
	BlocksPlacedLabel.RichText = false
	BlocksPlacedLabel.SelectionOrder = 0
	BlocksPlacedLabel.TextYAlignment = Enum.TextYAlignment.Center
	BlocksPlacedLabel.TextScaled = true
	BlocksPlacedLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	BlocksPlacedLabel.FontFace = Font.new("rbxasset://fonts/families/ComicNeueAngular.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	BlocksPlacedLabel.BorderMode = Enum.BorderMode.Outline
	BlocksPlacedLabel.Selectable = false
	BlocksPlacedLabel.OpenTypeFeatures = ""
	BlocksPlacedLabel.AnchorPoint = Vector2.new(0, 0)
	BlocksPlacedLabel.BorderColor = BrickColor.new("Really black")
	BlocksPlacedLabel.Visible = false
	BlocksPlacedLabel.TextXAlignment = Enum.TextXAlignment.Center
	BlocksPlacedLabel.AutomaticSize = Enum.AutomaticSize.None
	BlocksPlacedLabel.Size = UDim2.new(0.3955857455730438, 0, 0.2160000056028366, 0)
	BlocksPlacedLabel.TextWrapped = true
	BlocksPlacedLabel.TextWrap = true
	BlocksPlacedLabel.TextTransparency = 0
	BlocksPlacedLabel.ClipsDescendants = false
	BlocksPlacedLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
	BlocksPlacedLabel.Text = "BLOCKS PLACED:"
	BlocksPlacedLabel.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
	BlocksPlacedLabel.LineHeight = 1
	BlocksPlacedLabel.Rotation = 0
	BlocksPlacedLabel.Font = Enum.Font.Unknown
	BlocksPlacedLabel.BackgroundTransparency = 1
	BlocksPlacedLabel.Position = UDim2.new(0.5042445063591003, 0, 0.1459999978542328, 0)
	BlocksPlacedLabel.TextSize = 14
	BlocksPlacedLabel.MaxVisibleGraphemes = -1
	BlocksPlacedLabel.TextColor3 = Color3.fromRGB(0, 0, 0)
	BlocksPlacedLabel.Name = "BlocksPlacedLabel"
	return EasyBuildUI, BrickImage, Title, CloseCircle, TeamScroll,  TextButton, PlaceHolder, BlocksPlacedLabel
end

return ui
